//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFHelpers.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class WPFHelperSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static WPFHelperSettings defaultInstance = ((WPFHelperSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WPFHelperSettings())));
        
        public static WPFHelperSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MESSAGE_LOGMSG")]
        public string Message_LogMsg {
            get {
                return ((string)(this["Message_LogMsg"]));
            }
        }
    }
}
